# pytorch_lightning==2.1.0
seed_everything: 99
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'val_loss'
        patience: 10
        min_delta: 0.0
        mode: 'min'
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 1
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: 'val_loss'
        mode: min
        filename: 'best'
        save_last: true
        save_top_k: 1
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  num_enc: 4
  enc_dropout: 0.1
  num_enc_layers: 1
  num_hidden: 32
  num_lstm_layers: 1
data:
  machflow_data_path: "/data/basil/harmonized_basins.zarr/"
  features:
  - P
  - T
  targets:
  - Qmm
  stat_features:
  - P_mon_std
  - P_std
  - P_mean
  - T_mon_std
  - T_std
  - T_mean
  train_window_size: 1000
  window_min_count: 1
  train_num_samples_per_epoch: 100
  warmup_size: 365
  drop_all_nan_stations: true
  num_cv_folds: 6
  fold_nr: 0
  train_date_slice:
  - "1961-01-01"
  - "1998-12-31"
  valid_date_slice:
  - "1999-01-01"
  - "2008-12-31"
  test_date_slice:
  - "2009-01-01"
  - "2023-04-30"
  predict_date_slice:
  - "1961-01-01"
  - "2023-04-30"
  batch_size: 10
  num_workers: 0
  seed: 19
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    weight_decay: 0.001
ckpt_path: null
